use crate::LlmError;
use async_trait::async_trait;
use serde::{Deserialize, Serialize};

/// The role of a participant in a multi-turn conversation.
///
/// Maps directly to the `role` field in the OpenAI Chat Completions and
/// Anthropic Messages API request formats.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum LlmRole {
    /// Instructions given to the model before the conversation starts.
    System,
    /// A message from the human side of the conversation.
    User,
    /// A message generated by the model in a previous turn.
    Assistant,
}

/// A single message in a multi-turn LLM conversation.
///
/// **Caller**: All callers build a `Vec<LlmMessage>` and pass it to
/// `LlmProvider::complete`. The helper constructors (`system`, `user`,
/// `assistant`) are the idiomatic way to create messages.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmMessage {
    pub role: LlmRole,
    /// UTF-8 message text. For the vision endpoint the image is passed
    /// separately as raw bytes; `content` holds only the text prompt.
    pub content: String,
}

impl LlmMessage {
    /// Create a `System` message with the given content.
    ///
    /// **Why**: System messages set the model's persona and task context; they
    /// are always the first message in the slice passed to `complete`.
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            role: LlmRole::System,
            content: content.into(),
        }
    }

    /// Create a `User` message with the given content.
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            role: LlmRole::User,
            content: content.into(),
        }
    }

    /// Create an `Assistant` message with the given content.
    ///
    /// **Why**: Used when constructing few-shot examples or resuming a
    /// multi-turn conversation (e.g., the Telegram edit loop).
    pub fn assistant(content: impl Into<String>) -> Self {
        Self {
            role: LlmRole::Assistant,
            content: content.into(),
        }
    }
}

/// Pluggable LLM backend for text generation and image analysis.
///
/// Implemented by `ClaudeProvider`, `OpenAiProvider`, `OllamaProvider`, and
/// `MockLlmProvider` (for tests). All implementations are `Send + Sync` so
/// they can be shared across async tasks via `Arc<dyn LlmProvider>`.
///
/// **Caller**: Created once at startup by `create_provider(&llm_config)` and
/// injected into the email agent, offer generator, and volume estimator.
#[async_trait]
pub trait LlmProvider: Send + Sync {
    /// Generate a text completion from a conversation history.
    ///
    /// **Caller**: Email responder, Telegram edit parser, offer re-generation.
    ///
    /// # Parameters
    /// - `messages` — Ordered slice of conversation turns. The first message
    ///   should be a `System` message with the task context.
    ///
    /// # Returns
    /// The model's response as a plain UTF-8 string (assistant turn content).
    ///
    /// # Errors
    /// `LlmError::Api` when the provider returns a non-2xx status or an
    /// unparseable response. `LlmError::Network` on connection failures.
    async fn complete(&self, messages: &[LlmMessage]) -> Result<String, LlmError>;

    /// Analyse a single image and return a text description or structured output.
    ///
    /// **Caller**: `estimates/vision` route handler sends customer-uploaded room
    /// photos here to detect furniture and estimate volumes.
    ///
    /// # Parameters
    /// - `image_data` — Raw image bytes (JPEG or PNG).
    /// - `mime_type` — MIME type of the image (e.g., `"image/jpeg"`).
    /// - `prompt` — Text instruction for what to extract from the image
    ///   (e.g., a German JSON schema prompt listing furniture items).
    ///
    /// # Returns
    /// The model's text response; typically JSON that is then parsed into
    /// `VisionAnalysisResult`.
    ///
    /// # Errors
    /// Same as `complete`. Additionally `LlmError::Configuration` when the
    /// selected provider does not support vision (e.g., some Ollama models).
    async fn analyze_image(
        &self,
        image_data: &[u8],
        mime_type: &str,
        prompt: &str,
    ) -> Result<String, LlmError>;
}
