//! Direct XLSX template manipulation for invoice (Rechnung) generation.
//!
//! Uses the same XML-surgery approach as `xlsx.rs` (offer generator),
//! delegating cell-value writes, row hiding, and formula-cache stripping
//! to the shared functions exported from that module.
//!
//! ## Template
//!
//! The invoice generator uses `templates/Rechnung_Vorlage_v2.xlsx`, which is a
//! copy of `offer_template.xlsx` with only four static label strings patched in
//! `xl/sharedStrings.xml` (via `scripts/make_rechnung_template.py`):
//!
//! | KVA label            | Invoice label     |
//! |----------------------|-------------------|
//! | Kostenvoranschlag    | Rechnung          |
//! | Angebots-Nr.         | Rechnungs-Nr.     |
//! | Angebotsdatum        | Rechnungsdatum    |
//! | Angebot gültig bis   | Zahlungsziel      |
//!
//! All cell layout, styling, logo, formulas, and footer are preserved
//! bit-for-bit from the KVA template.
//!
//! ## Template layout (rows / columns)
//!
//! Invoice template layout (Rechnung_Vorlage_v2.xlsx) — identical to KVA:
//! - **Address block**: A8–A11 (customer), G15 (date)
//! - **Title**: A16 (e.g. "Rechnung Nr. 2026-0042")
//! - **Details**: B17 (Leistungsdatum), B18 (phone / contact), F18 (email)
//! - **Salutation**: A20
//! - **Locations**: A26–A28 (origin), F26–F28 (destination)
//! - **Volume label**: A29
//! - **Line items**: rows 31–46, columns A-G
//!   - A-B (merged): Beschreibung
//!   - C: Bemerkung / Remark
//!   - D: (blank spacer)
//!   - E: Menge (quantity)
//!   - F: Einzelpreis (€/unit, may be negative for credits)
//!   - G: Gesamt Netto (formula `=F*E` or flat value)
//! - **Totals**: G48 = SUM(G31:G46), G49 = 19% MwSt, G51 = Bruttobetrag
//! - **Workers helper**: J50 (kept for formula compatibility; set to 1 for invoices)
//!
//! ## Negative line items (Gutschrift / Anzahlungsabzug)
//!
//! `unit_price` may be negative. The arithmetic propagates correctly through
//! the SUM formula in G48 — no special handling needed. Negative values render
//! with a leading minus sign in the € cell style inherited from the template.

use crate::xlsx::{
    hide_row, set_cell_value, strip_formula_cached_values, unhide_row, CellValue,
};
use crate::OfferError;
use chrono::NaiveDate;
use serde::{Deserialize, Serialize};
use std::io::{Cursor, Read, Write};
use zip::write::SimpleFileOptions;
use zip::{ZipArchive, ZipWriter};

/// The invoice template XLSX — embedded at compile time.
///
/// `Rechnung_Vorlage_v2.xlsx` is generated by `scripts/make_rechnung_template.py`:
/// it copies `offer_template.xlsx` and patches only the four static header
/// label strings in `xl/sharedStrings.xml` (Kostenvoranschlag → Rechnung, etc.).
/// All styling, formulas, logo, and footer are preserved from the KVA template.
const TEMPLATE_BYTES: &[u8] = include_bytes!("../../../templates/Rechnung_Vorlage_v2.xlsx");

/// First row used for line items in the invoice template.
const LINE_ITEM_START_ROW: u32 = 31;
/// Last row used for line items in the invoice template (rows 31–46 = 16 slots).
const LINE_ITEM_END_ROW: u32 = 46;
/// Maximum number of line item rows in the invoice template (rows 31–46).
const MAX_LINE_ITEMS: usize = 16;

// Style indices from the KVA template's xl/styles.xml — reused for invoice.
// These index into the shared styleSheet and are stable across both templates
// because Rechnung_Vorlage_v2.xlsx is derived from offer_template.xlsx.
const STYLES_AB: [&str; 2] = ["58", "53"]; // Description cols A,B: white / blue
const STYLES_C: [&str; 2] = ["59", "54"];  // Remark col C
const STYLES_DE: [&str; 2] = ["60", "55"]; // Quantity cols D,E
const STYLES_F: [&str; 2] = ["61", "56"];  // Unit-price col F (€)
const STYLES_G: [&str; 2] = ["84", "83"];  // Total col G (right-aligned €)

// ---------------------------------------------------------------------------
// Public data types
// ---------------------------------------------------------------------------

/// All data needed to fill the Rechnung XLSX template for one invoice.
///
/// **Caller**: `crates/api/src/routes/invoices.rs`
/// **Why**: Single transfer object between the HTTP route and the XLSX generator.
///
/// Line items are the single source of truth for what appears on the invoice:
/// - **Full**: copied from offer line items + any on-site extras/credits
/// - **PartialFirst**: single Anzahlung line item
/// - **PartialFinal**: offer line items + extras + "Abzgl. Anzahlung" deduction
#[derive(Debug, Clone)]
pub struct InvoiceData {
    /// Invoice number printed in the heading, e.g. `"1-2026"`.
    pub invoice_number: String,
    /// Invoice type — determines the base line item description.
    pub invoice_type: InvoiceType,
    /// Invoice creation date written to G15.
    pub invoice_date: NaiveDate,
    /// Moving date written to B17 (Leistungsdatum). `None` → blank.
    pub service_date: Option<NaiveDate>,
    /// Customer full name for the address block (A8).
    pub customer_name: String,
    /// Customer email address (F18). Optional because some customers don't have email.
    pub customer_email: Option<String>,
    /// Company name for business customers — rendered above customer name in the address block.
    pub company_name: Option<String>,
    /// Attention line for business customers, e.g. `"z.Hd. Herrn Schmidt"`.
    pub attention_line: Option<String>,
    /// Billing street + house number (A10).
    pub billing_street: String,
    /// Billing postal code + city, e.g. `"31135 Hildesheim"` (A11).
    pub billing_city: String,
    /// Offer number used in line item descriptions, e.g. `"2026-0042"`.
    pub offer_number: String,
    /// Formal salutation line, e.g. `"Sehr geehrter Herr Müller,"`.
    pub salutation: String,
    /// Line items for the invoice — the single source of truth.
    /// Each item has pos, description, quantity, unit_price (EUR, may be negative for credits),
    /// and optional remark. Maximum 16 items (rows 31–46).
    pub line_items: Vec<InvoiceLineItem>,

    // ── Legacy fields (kept for backward compatibility during migration) ──

    /// **Legacy**: Netto amount for the base line item in cents.
    /// Only used when `line_items` is empty (pre-migration invoices).
    #[deprecated(note = "Use line_items instead. base_netto_cents is derived from line items.")]
    pub base_netto_cents: i64,
    /// **Legacy**: Extra services appended as additional line items.
    /// Only used when `line_items` is empty (pre-migration invoices).
    #[deprecated(note = "Use line_items instead. Extra services are now part of line_items.")]
    pub extra_services: Vec<ExtraService>,
    /// **Legacy**: Origin street + house number (A10, A27).
    /// Only used when `billing_street` is empty.
    #[deprecated(note = "Use billing_street instead.")]
    pub origin_street: String,
    /// **Legacy**: Origin postal code + city (A11).
    /// Only used when `billing_city` is empty.
    #[deprecated(note = "Use billing_city instead.")]
    pub origin_city: String,
}

/// A single line item on an invoice.
///
/// **Caller**: `crates/api/src/routes/invoices.rs` — created from offer line items + on-site edits
/// **Why**: Invoices now itemise individual services (like offers), with optional on-site
/// extras (Zusatzleistungen) and credits/refunds (Gutschriften, negative unit_price).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct InvoiceLineItem {
    /// Position number displayed in column A (1, 2, 3, …).
    pub pos: u32,
    /// Description shown in column B, e.g. `"De/Montage"` or `"Gutschrift: beschädigter Schrank"`.
    pub description: String,
    /// Quantity shown in column C. Default 1 for most services.
    pub quantity: f64,
    /// Netto unit price in euros (not cents!). May be negative for credits/refunds.
    /// Negative values propagate correctly through the G-column SUM formula.
    pub unit_price: f64,
    /// Optional remark appended in column C, e.g. `"Entladestelle"`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remark: Option<String>,
}

/// A single extra service sold on-site.
///
/// **Legacy**: Kept for backward compatibility with pre-migration invoices.
/// New code should use `InvoiceLineItem` instead.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExtraService {
    /// Short description shown in column B, e.g. `"Klaviertransport"`.
    pub description: String,
    /// Netto price in cents. Written to Einzelpreis (F column).
    pub price_cents: i64,
}

/// Determines the base line item description and amount split logic.
#[derive(Debug, Clone, PartialEq)]
pub enum InvoiceType {
    /// Single invoice for the full job amount.
    Full,
    /// First of two partial invoices — Anzahlung at `percent`%.
    PartialFirst { percent: u8 },
    /// Second of two partial invoices — Restbetrag for the remaining amount.
    PartialFinal,
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/// Generate a complete invoice XLSX from the embedded Rechnung_Vorlage_v2 template.
///
/// **Caller**: `crates/api/src/routes/invoices.rs` (create + regenerate paths)
/// **Why**: Fills the XLSX template with per-invoice data using the same XML-surgery
/// approach as the offer generator, delegating cell writes and row hiding to shared
/// functions from `xlsx.rs`.
///
/// The template is `Rechnung_Vorlage_v2.xlsx` — a copy of `offer_template.xlsx` with
/// only the four static header labels patched (Kostenvoranschlag → Rechnung, etc.).
/// All column layout, styling, logo, totals block (Netto/MwSt/Brutto), and footer
/// are identical to the KVA template.
///
/// **Negative line items**: `unit_price` may be negative (Gutschrift / Anzahlungsabzug).
/// Negative values flow through the `=F*E` formula in column G and the SUM in G48
/// without any special handling — Excel/LibreOffice arithmetic handles sign correctly.
///
/// # Parameters
/// - `data` — fully populated `InvoiceData`
///
/// # Returns
/// Raw bytes of a valid `.xlsx` file ready to pass to `convert_xlsx_to_pdf`.
///
/// # Errors
/// - `OfferError::Template` if the template ZIP is corrupt or not valid UTF-8
/// - `OfferError::Template` if ZIP reassembly fails
pub fn generate_invoice_xlsx(data: &InvoiceData) -> Result<Vec<u8>, OfferError> {
    let mut template_zip = ZipArchive::new(Cursor::new(TEMPLATE_BYTES))
        .map_err(|e| OfferError::Template(format!("Failed to read invoice template ZIP: {e}")))?;

    // Build cell modifications and determine which rows are used
    let (cell_mods, hidden_rows, unhidden_rows) = build_cell_modifications(data);

    // Read sheet1.xml
    let sheet1_xml = read_zip_entry(&mut template_zip, "xl/worksheets/sheet1.xml")?;
    let sheet1_str = String::from_utf8(sheet1_xml)
        .map_err(|e| OfferError::Template(format!("sheet1.xml not valid UTF-8: {e}")))?;

    // Apply cell modifications
    let mut modified_sheet1 = sheet1_str;
    for (cell_ref, value) in &cell_mods {
        modified_sheet1 = set_cell_value(&modified_sheet1, cell_ref, value);
    }

    // Hide/unhide line-item rows — mirrors the offer template approach
    for &row in &hidden_rows {
        modified_sheet1 = hide_row(&modified_sheet1, row);
    }
    for &row in &unhidden_rows {
        modified_sheet1 = unhide_row(&modified_sheet1, row);
    }

    // Strip stale formula caches so LibreOffice recalculates on open
    modified_sheet1 = strip_formula_cached_values(&modified_sheet1);

    // Remove hyperlinks section (same as offer generator — email as plain text)
    modified_sheet1 = strip_hyperlinks(&modified_sheet1);

    // Read workbook.xml and force recalculation on load + fix print area
    let workbook_xml = read_zip_entry(&mut template_zip, "xl/workbook.xml")?;
    let workbook_str = String::from_utf8(workbook_xml)
        .map_err(|e| OfferError::Template(format!("workbook.xml not valid UTF-8: {e}")))?;
    let modified_workbook = modify_invoice_workbook(&workbook_str);

    // Fix date format in styles.xml: m/d/yyyy → dd.mm.yyyy (German)
    let styles_xml = read_zip_entry(&mut template_zip, "xl/styles.xml")?;
    let styles_str = String::from_utf8(styles_xml)
        .map_err(|e| OfferError::Template(format!("styles.xml not valid UTF-8: {e}")))?;
    let modified_styles = styles_str.replace(
        r#"formatCode="m/d/yyyy""#,
        r#"formatCode="dd.mm.yyyy""#,
    );

    // Read sheet1 rels and strip hyperlink relationships (keep drawing rel)
    let sheet1_rels_xml =
        read_zip_entry(&mut template_zip, "xl/worksheets/_rels/sheet1.xml.rels")?;
    let sheet1_rels_str = String::from_utf8(sheet1_rels_xml)
        .map_err(|e| OfferError::Template(format!("sheet1.xml.rels not valid UTF-8: {e}")))?;
    let modified_sheet1_rels = strip_hyperlink_rels(&sheet1_rels_str);

    // Reassemble ZIP
    assemble_invoice_xlsx(
        &mut template_zip,
        &modified_sheet1,
        &modified_workbook,
        &modified_styles,
        &modified_sheet1_rels,
    )
}

// ---------------------------------------------------------------------------
// Cell modification builder
// ---------------------------------------------------------------------------

/// Build the list of cell value changes for this invoice, plus row visibility lists.
///
/// Returns `(cell_modifications, hidden_rows, unhidden_rows)`.
///
/// Column layout — identical to KVA template (rows 31-46):
/// - A-B (merged): Beschreibung
/// - C: Bemerkung
/// - D: (blank spacer)
/// - E: Menge
/// - F: Einzelpreis (may be negative for credits)
/// - G: Gesamt Netto (formula `=IF(E="",0,F*E)`)
///
/// Totals block (row numbers reflect KVA template structure):
/// - G48 = SUM(G31:G46) — Nettosumme
/// - G49 = 19% MwSt formula
/// - G51 = Bruttobetrag formula
fn build_cell_modifications(
    data: &InvoiceData,
) -> (Vec<(String, CellValue)>, Vec<u32>, Vec<u32>) {
    let mut mods = Vec::new();

    // Resolve effective address fields (prefer new, fall back to legacy)
    let billing_street = if data.billing_street.is_empty() {
        #[allow(deprecated)]
        data.origin_street.clone()
    } else {
        data.billing_street.clone()
    };
    let billing_city = if data.billing_city.is_empty() {
        #[allow(deprecated)]
        data.origin_city.clone()
    } else {
        data.billing_city.clone()
    };

    // ── Address block ──────────────────────────────────────────────────────
    // For business customers: A8 = company name, A9 = attention line
    // For private customers:  A8 = customer name, A9 = email (or blank)
    if let Some(ref company) = data.company_name {
        mods.push(("A8".into(), CellValue::Text(company.clone())));
        let attn = data
            .attention_line
            .clone()
            .filter(|s| !s.is_empty())
            .or_else(|| data.customer_email.clone())
            .unwrap_or_default();
        mods.push(("A9".into(), CellValue::Text(attn)));
    } else {
        mods.push(("A8".into(), CellValue::Text(data.customer_name.clone())));
        mods.push((
            "A9".into(),
            CellValue::Text(data.customer_email.clone().unwrap_or_default()),
        ));
    }
    mods.push(("A10".into(), CellValue::Text(billing_street.clone())));
    mods.push(("A11".into(), CellValue::Text(billing_city.clone())));

    // ── Date (G15) and clear G14 TODAY() formula ──────────────────────────
    mods.push(("G14".into(), CellValue::Text(String::new())));
    mods.push((
        "G15".into(),
        CellValue::Text(data.invoice_date.format("%d.%m.%Y").to_string()),
    ));

    // ── Title: invoice number (A16) ────────────────────────────────────────
    mods.push((
        "A16".into(),
        CellValue::Text(format!("Rechnung Nr. {}", data.invoice_number)),
    ));

    // ── Leistungsdatum (B17) and email (F18) ──────────────────────────────
    let service_date_str = data
        .service_date
        .map(|d| d.format("%d.%m.%Y").to_string())
        .unwrap_or_default();
    mods.push(("B17".into(), CellValue::Text(service_date_str)));
    if let Some(ref email) = data.customer_email {
        mods.push(("F18".into(), CellValue::StyledText(email.clone(), "0")));
    }

    // ── Salutation / greeting (A20) ────────────────────────────────────────
    mods.push(("A20".into(), CellValue::Text(data.salutation.clone())));

    // ── Job location line (A27) ────────────────────────────────────────────
    // Reuses the A27 cell from the KVA template (origin city row) to show
    // "Auftragsort: <street>, <city>".
    mods.push((
        "A27".into(),
        CellValue::Text(format!(
            "Auftragsort:  {}, {}",
            billing_street, billing_city
        )),
    ));

    // ── Line items (rows 31–46) ────────────────────────────────────────────
    //
    // Style pairs indexed by [color]: 0 = white (fill 4), 1 = blue (fill 3)
    // Style indices are shared with the KVA template (same styles.xml).

    // 1. Hide ALL line-item rows and pre-clear E/F to avoid stale preset values
    let mut hidden_rows: Vec<u32> = (LINE_ITEM_START_ROW..=LINE_ITEM_END_ROW).collect();
    let mut unhidden_rows: Vec<u32> = Vec::new();

    for row in LINE_ITEM_START_ROW..=LINE_ITEM_END_ROW {
        mods.push((format!("E{row}"), CellValue::Number(0.0)));
        mods.push((format!("F{row}"), CellValue::Number(0.0)));
    }

    // 2. Resolve effective line items: prefer new field, fall back to legacy model
    let items_owned: Vec<InvoiceLineItem>;
    #[allow(deprecated)]
    let effective_items: &[InvoiceLineItem] = if !data.line_items.is_empty() {
        &data.line_items
    } else {
        items_owned = build_legacy_line_items(data);
        &items_owned
    };

    if effective_items.len() > MAX_LINE_ITEMS {
        tracing::warn!(
            invoice_number = %data.invoice_number,
            total_items = effective_items.len(),
            max_items = MAX_LINE_ITEMS,
            "Invoice has {} line items but template only has {} slots (rows {}-{}). \
             Excess items will be truncated in PDF.",
            effective_items.len(),
            MAX_LINE_ITEMS,
            LINE_ITEM_START_ROW,
            LINE_ITEM_END_ROW,
        );
    }

    // 3. Write items sequentially, alternating white/blue styles
    for (i, item) in effective_items.iter().take(MAX_LINE_ITEMS).enumerate() {
        let row = LINE_ITEM_START_ROW + i as u32;
        let color = 1 - i % 2; // 1 = blue (first row), 0 = white

        unhidden_rows.push(row);

        // Column A (merged with B): Beschreibung
        mods.push((
            format!("A{row}"),
            CellValue::StyledText(item.description.clone(), STYLES_AB[color]),
        ));
        // Column B (merge partner): keep styled, content ignored
        mods.push((
            format!("B{row}"),
            CellValue::StyledText(String::new(), STYLES_AB[color]),
        ));
        // Column C: Bemerkung / remark
        let remark = item.remark.as_deref().unwrap_or("");
        mods.push((
            format!("C{row}"),
            CellValue::StyledText(remark.to_string(), STYLES_C[color]),
        ));
        // Column D: blank spacer
        mods.push((
            format!("D{row}"),
            CellValue::StyledText(String::new(), STYLES_DE[color]),
        ));
        // Column E: Menge (quantity)
        mods.push((
            format!("E{row}"),
            CellValue::StyledNumber(item.quantity, STYLES_DE[color]),
        ));
        // Column F: Einzelpreis (€, may be negative)
        mods.push((
            format!("F{row}"),
            CellValue::StyledNumber(item.unit_price, STYLES_F[color]),
        ));
        // Column G: Gesamt Netto = F * E  (negative unit_price → negative total)
        let formula = format!("IF(E{row}=\"\",0,F{row}*E{row})");
        mods.push((
            format!("G{row}"),
            CellValue::StyledFormula(formula, STYLES_G[color]),
        ));
    }

    // Remove unhidden rows from hidden list
    hidden_rows.retain(|r| !unhidden_rows.contains(r));

    // 4. Rewrite totals-block SUM to cover all 16 line-item rows (31–46)
    //    G48 = Nettosumme, G49 = 19% MwSt, G51 = Bruttobetrag
    //    Style "72" = right-aligned € total (same as KVA G44 rewrite).
    mods.push((
        "G48".into(),
        CellValue::StyledFormula("SUM(G31:G46)".into(), "72"),
    ));

    // J50 is a helper cell (persons/workers) used by labor formulas in the KVA.
    // For invoices we don't have labor formula rows, but set it to 1 for safety
    // in case the template has any residual references.
    mods.push(("J50".into(), CellValue::Number(1.0)));

    (mods, hidden_rows, unhidden_rows)
}

/// Build line items from the legacy `base_netto_cents` + `extra_services` model.
#[allow(deprecated)]
fn build_legacy_line_items(data: &InvoiceData) -> Vec<InvoiceLineItem> {
    let mut items = Vec::new();

    let base_description = match &data.invoice_type {
        InvoiceType::Full => format!(
            "Umzugsdienstleistung gemäß Angebot Nr. {}",
            data.offer_number
        ),
        InvoiceType::PartialFirst { percent } => format!(
            "Anzahlung ({}%) — Umzugsdienstleistung gemäß Angebot Nr. {}",
            percent, data.offer_number
        ),
        InvoiceType::PartialFinal => format!(
            "Restbetrag — Umzugsdienstleistung gemäß Angebot Nr. {}",
            data.offer_number
        ),
    };
    let base_netto_euros = data.base_netto_cents as f64 / 100.0;
    items.push(InvoiceLineItem {
        pos: 1,
        description: base_description,
        quantity: 1.0,
        unit_price: base_netto_euros,
        remark: None,
    });

    for (i, extra) in data.extra_services.iter().take(15).enumerate() {
        let extra_euros = extra.price_cents as f64 / 100.0;
        items.push(InvoiceLineItem {
            pos: (i + 2) as u32,
            description: extra.description.clone(),
            quantity: 1.0,
            unit_price: extra_euros,
            remark: None,
        });
    }

    items
}

// ---------------------------------------------------------------------------
// Workbook modification
// ---------------------------------------------------------------------------

/// Patch `workbook.xml`: fix print area to A:H and force recalculation on load.
///
/// Same approach as the KVA generator: limits PDF output to columns A-H only
/// (avoids printing the helper columns I-P including J50).
fn modify_invoice_workbook(xml: &str) -> String {
    let mut result = xml.to_string();

    // Fix print area: replace dual-range with A:H only
    if let Some(start) = result.find("_xlnm.Print_Area") {
        if let Some(content_start) = result[start..].find('>') {
            let abs_content_start = start + content_start + 1;
            if let Some(end_tag) = result[abs_content_start..].find("</definedName>") {
                let abs_end = abs_content_start + end_tag;
                let mut patched = String::with_capacity(result.len());
                patched.push_str(&result[..abs_content_start]);
                patched.push_str("Tabelle1!$A$1:$H$120");
                patched.push_str(&result[abs_end..]);
                result = patched;
            }
        }
    }

    // Force full recalculation on load
    if result.contains(r#"fullCalcOnLoad="0""#) {
        result = result.replace(r#"fullCalcOnLoad="0""#, r#"fullCalcOnLoad="1""#);
    } else if !result.contains("fullCalcOnLoad=") {
        if let Some(pos) = result.find("<calcPr") {
            let after = &result[pos..];
            if let Some(gt) = after.find("/>") {
                let slash_offset = 1; // point before "/>"
                let insert_at = pos + gt - slash_offset + 1;
                result.insert_str(insert_at, r#" fullCalcOnLoad="true""#);
            }
        }
    }

    result
}

// ---------------------------------------------------------------------------
// Hyperlink stripping (same as KVA generator)
// ---------------------------------------------------------------------------

/// Remove the `<hyperlinks>` block from `sheet1.xml` so email addresses render
/// as plain text rather than clickable hyperlinks.
fn strip_hyperlinks(xml: &str) -> String {
    if let Some(start) = xml.find("<hyperlinks>") {
        if let Some(end) = xml.find("</hyperlinks>") {
            let mut result = String::with_capacity(xml.len());
            result.push_str(&xml[..start]);
            result.push_str(&xml[end + "</hyperlinks>".len()..]);
            return result;
        }
    }
    xml.to_string()
}

/// Remove hyperlink `<Relationship>` entries from `sheet1.xml.rels`, keeping
/// the drawing relationship.
fn strip_hyperlink_rels(rels_xml: &str) -> String {
    // Remove any Relationship element with Type containing "hyperlink"
    let mut result = String::with_capacity(rels_xml.len());
    let mut pos = 0;
    while pos < rels_xml.len() {
        if let Some(rel_start) = rels_xml[pos..].find("<Relationship ") {
            let abs_start = pos + rel_start;
            if let Some(rel_end) = rels_xml[abs_start..].find("/>") {
                let abs_end = abs_start + rel_end + 2;
                let rel_fragment = &rels_xml[abs_start..abs_end];
                if rel_fragment.contains("hyperlink") {
                    // Skip this element
                    result.push_str(&rels_xml[pos..abs_start]);
                    pos = abs_end;
                    continue;
                }
            }
        }
        // No more Relationship elements — copy remainder
        result.push_str(&rels_xml[pos..]);
        break;
    }
    result
}

// ---------------------------------------------------------------------------
// ZIP utilities
// ---------------------------------------------------------------------------

fn read_zip_entry(
    zip: &mut ZipArchive<Cursor<&'static [u8]>>,
    name: &str,
) -> Result<Vec<u8>, OfferError> {
    let mut entry = zip
        .by_name(name)
        .map_err(|e| OfferError::Template(format!("Entry '{name}' not found in template: {e}")))?;
    let mut buf = Vec::new();
    entry
        .read_to_end(&mut buf)
        .map_err(|e| OfferError::Template(format!("Failed to read '{name}': {e}")))?;
    Ok(buf)
}

fn assemble_invoice_xlsx(
    template_zip: &mut ZipArchive<Cursor<&'static [u8]>>,
    modified_sheet1: &str,
    modified_workbook: &str,
    modified_styles: &str,
    modified_sheet1_rels: &str,
) -> Result<Vec<u8>, OfferError> {
    let buf: Vec<u8> = Vec::new();
    let cursor = Cursor::new(buf);
    let mut writer = ZipWriter::new(cursor);
    let options = SimpleFileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated);

    for i in 0..template_zip.len() {
        let mut entry = template_zip
            .by_index(i)
            .map_err(|e| OfferError::Template(format!("Failed to read ZIP entry {i}: {e}")))?;
        let name = entry.name().to_string();

        writer
            .start_file(&name, options)
            .map_err(|e| OfferError::Template(format!("Failed to start ZIP entry '{name}': {e}")))?;

        match name.as_str() {
            "xl/worksheets/sheet1.xml" => {
                writer
                    .write_all(modified_sheet1.as_bytes())
                    .map_err(|e| OfferError::Template(format!("Failed to write sheet1.xml: {e}")))?;
            }
            "xl/workbook.xml" => {
                writer
                    .write_all(modified_workbook.as_bytes())
                    .map_err(|e| OfferError::Template(format!("Failed to write workbook.xml: {e}")))?;
            }
            "xl/styles.xml" => {
                writer
                    .write_all(modified_styles.as_bytes())
                    .map_err(|e| OfferError::Template(format!("Failed to write styles.xml: {e}")))?;
            }
            "xl/worksheets/_rels/sheet1.xml.rels" => {
                writer
                    .write_all(modified_sheet1_rels.as_bytes())
                    .map_err(|e| {
                        OfferError::Template(format!("Failed to write sheet1.xml.rels: {e}"))
                    })?;
            }
            _ => {
                let mut content = Vec::new();
                entry
                    .read_to_end(&mut content)
                    .map_err(|e| OfferError::Template(format!("Failed to read '{name}': {e}")))?;
                writer
                    .write_all(&content)
                    .map_err(|e| OfferError::Template(format!("Failed to write '{name}': {e}")))?;
            }
        }
    }

    let finished = writer
        .finish()
        .map_err(|e| OfferError::Template(format!("Failed to finalise invoice ZIP: {e}")))?;
    Ok(finished.into_inner())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_data() -> InvoiceData {
        #[allow(deprecated)]
        InvoiceData {
            invoice_number: "2026-0001".into(),
            invoice_type: InvoiceType::Full,
            invoice_date: NaiveDate::from_ymd_opt(2026, 4, 19).unwrap(),
            service_date: Some(NaiveDate::from_ymd_opt(2026, 4, 15).unwrap()),
            customer_name: "Max Mustermann".into(),
            customer_email: Some("max@example.com".into()),
            company_name: None,
            attention_line: None,
            billing_street: "Musterstraße 1".into(),
            billing_city: "31135 Hildesheim".into(),
            offer_number: "2026-0042".into(),
            salutation: "Sehr geehrter Herr Mustermann,".into(),
            line_items: vec![
                InvoiceLineItem {
                    pos: 1,
                    description: "Umzugsdienstleistung".into(),
                    quantity: 1.0,
                    unit_price: 1000.0,
                    remark: None,
                },
                InvoiceLineItem {
                    pos: 2,
                    description: "Gutschrift: beschädigter Schrank".into(),
                    quantity: 1.0,
                    unit_price: -50.0, // negative — credit
                    remark: Some("Anzahlungsabzug".into()),
                },
            ],
            base_netto_cents: 0,
            extra_services: vec![],
            origin_street: String::new(),
            origin_city: String::new(),
        }
    }

    #[test]
    fn test_generate_invoice_xlsx_returns_bytes() {
        let data = sample_data();
        let result = generate_invoice_xlsx(&data);
        assert!(result.is_ok(), "generate_invoice_xlsx failed: {:?}", result.err());
        let bytes = result.unwrap();
        assert!(bytes.len() > 1000, "XLSX output suspiciously small: {} bytes", bytes.len());
        // Verify it's a valid ZIP (XLSX = ZIP)
        assert_eq!(&bytes[0..4], b"PK\x03\x04", "Output is not a valid ZIP/XLSX");
    }

    #[test]
    fn test_negative_unit_price_does_not_panic() {
        let data = sample_data();
        // Should not panic with negative prices
        let result = generate_invoice_xlsx(&data);
        assert!(result.is_ok());
    }

    #[test]
    fn test_partial_first_invoice() {
        #[allow(deprecated)]
        let data = InvoiceData {
            invoice_number: "2026-0002".into(),
            invoice_type: InvoiceType::PartialFirst { percent: 30 },
            invoice_date: NaiveDate::from_ymd_opt(2026, 4, 19).unwrap(),
            service_date: None,
            customer_name: "Erika Musterfrau".into(),
            customer_email: None,
            company_name: None,
            attention_line: None,
            billing_street: "Bahnhofstr. 5".into(),
            billing_city: "30159 Hannover".into(),
            offer_number: "2026-0010".into(),
            salutation: "Sehr geehrte Frau Musterfrau,".into(),
            line_items: vec![InvoiceLineItem {
                pos: 1,
                description: "Anzahlung (30%) — gemäß Angebot Nr. 2026-0010".into(),
                quantity: 1.0,
                unit_price: 357.14,
                remark: None,
            }],
            base_netto_cents: 0,
            extra_services: vec![],
            origin_street: String::new(),
            origin_city: String::new(),
        };
        let result = generate_invoice_xlsx(&data);
        assert!(result.is_ok());
    }

    #[test]
    fn test_legacy_line_items_fallback() {
        #[allow(deprecated)]
        let data = InvoiceData {
            invoice_number: "2026-0003".into(),
            invoice_type: InvoiceType::Full,
            invoice_date: NaiveDate::from_ymd_opt(2026, 4, 19).unwrap(),
            service_date: None,
            customer_name: "Legacy Customer".into(),
            customer_email: None,
            company_name: None,
            attention_line: None,
            billing_street: "Altgasse 7".into(),
            billing_city: "12345 Altstadt".into(),
            offer_number: "2025-0099".into(),
            salutation: "Sehr geehrte Damen und Herren,".into(),
            line_items: vec![], // empty → triggers legacy path
            base_netto_cents: 84034,
            extra_services: vec![ExtraService {
                description: "Klaviertransport".into(),
                price_cents: 15000,
            }],
            origin_street: String::new(),
            origin_city: String::new(),
        };
        let result = generate_invoice_xlsx(&data);
        assert!(result.is_ok());
    }

    #[test]
    fn test_max_line_items_no_panic() {
        #[allow(deprecated)]
        let mut data = sample_data();
        // Fill 20 items — should truncate to 16, not panic
        data.line_items = (1..=20)
            .map(|i| InvoiceLineItem {
                pos: i,
                description: format!("Posten {i}"),
                quantity: 1.0,
                unit_price: 100.0 * i as f64,
                remark: None,
            })
            .collect();
        let result = generate_invoice_xlsx(&data);
        assert!(result.is_ok());
    }
}
